version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "jquery",
    "browser",
    "cypress",
    "jest"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "yapf"