environment: development

apphost: k8s

label:
  name: proxy

container:
  name: proxy
  pullPolicy: IfNotPresent
  image: ghcr.io/hutechcj/profio-proxy
  tag: latest
  port: 80
replicas: 3

service:
  port: 8888
  type: ClusterIP

resources:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: profio-proxy.k8s.hutechcj.com
      paths:
        - /
  tls:
    - secretName: profio-proxy-tls
      hosts:
        - profio-proxy.k8s.hutechcj.com

serviceMonitor:
  enabled: true

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 10"]

terminationGracePeriodSeconds: 30

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

deployment:
  annotations: {}
