/*
 Navicat Premium Data Transfer

 Source Server         : RemotePostgre
 Source Server Type    : PostgreSQL
 Source Server Version : 150004 (150004)
 Source Host           : dpg-cjl2klfv9s6c73arft2g-a.singapore-postgres.render.com:5432
 Source Catalog        : profio
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150004 (150004)
 File Encoding         : 65001

 Date: 30/08/2023 21:16:40
*/


-- ----------------------------
-- Sequence structure for AspNetRoleClaims_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."AspNetRoleClaims_Id_seq";
CREATE SEQUENCE "public"."AspNetRoleClaims_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for AspNetUserClaims_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."AspNetUserClaims_Id_seq";
CREATE SEQUENCE "public"."AspNetUserClaims_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for AspNetRoleClaims
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetRoleClaims";
CREATE TABLE "public"."AspNetRoleClaims" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "RoleId" text COLLATE "pg_catalog"."default" NOT NULL,
  "ClaimType" text COLLATE "pg_catalog"."default",
  "ClaimValue" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of AspNetRoleClaims
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetRoles
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetRoles";
CREATE TABLE "public"."AspNetRoles" (
  "Id" text COLLATE "pg_catalog"."default" NOT NULL,
  "Name" varchar(256) COLLATE "pg_catalog"."default",
  "NormalizedName" varchar(256) COLLATE "pg_catalog"."default",
  "ConcurrencyStamp" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of AspNetRoles
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetUserClaims
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetUserClaims";
CREATE TABLE "public"."AspNetUserClaims" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "UserId" text COLLATE "pg_catalog"."default" NOT NULL,
  "ClaimType" text COLLATE "pg_catalog"."default",
  "ClaimValue" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of AspNetUserClaims
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetUserLogins
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetUserLogins";
CREATE TABLE "public"."AspNetUserLogins" (
  "LoginProvider" text COLLATE "pg_catalog"."default" NOT NULL,
  "ProviderKey" text COLLATE "pg_catalog"."default" NOT NULL,
  "ProviderDisplayName" text COLLATE "pg_catalog"."default",
  "UserId" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of AspNetUserLogins
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetUserRoles
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetUserRoles";
CREATE TABLE "public"."AspNetUserRoles" (
  "UserId" text COLLATE "pg_catalog"."default" NOT NULL,
  "RoleId" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of AspNetUserRoles
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetUserTokens
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetUserTokens";
CREATE TABLE "public"."AspNetUserTokens" (
  "UserId" text COLLATE "pg_catalog"."default" NOT NULL,
  "LoginProvider" text COLLATE "pg_catalog"."default" NOT NULL,
  "Name" text COLLATE "pg_catalog"."default" NOT NULL,
  "Value" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of AspNetUserTokens
-- ----------------------------

-- ----------------------------
-- Table structure for AspNetUsers
-- ----------------------------
DROP TABLE IF EXISTS "public"."AspNetUsers";
CREATE TABLE "public"."AspNetUsers" (
  "Id" text COLLATE "pg_catalog"."default" NOT NULL,
  "FullName" text COLLATE "pg_catalog"."default",
  "UserName" varchar(256) COLLATE "pg_catalog"."default",
  "NormalizedUserName" varchar(256) COLLATE "pg_catalog"."default",
  "Email" varchar(256) COLLATE "pg_catalog"."default",
  "NormalizedEmail" varchar(256) COLLATE "pg_catalog"."default",
  "EmailConfirmed" bool NOT NULL,
  "PasswordHash" text COLLATE "pg_catalog"."default",
  "SecurityStamp" text COLLATE "pg_catalog"."default",
  "ConcurrencyStamp" text COLLATE "pg_catalog"."default",
  "PhoneNumber" text COLLATE "pg_catalog"."default",
  "PhoneNumberConfirmed" bool NOT NULL,
  "TwoFactorEnabled" bool NOT NULL,
  "LockoutEnd" timestamptz(6),
  "LockoutEnabled" bool NOT NULL,
  "AccessFailedCount" int4 NOT NULL
)
;

-- ----------------------------
-- Records of AspNetUsers
-- ----------------------------

-- ----------------------------
-- Table structure for Customers
-- ----------------------------
DROP TABLE IF EXISTS "public"."Customers";
CREATE TABLE "public"."Customers" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "Name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Phone" char(10) COLLATE "pg_catalog"."default" NOT NULL,
  "Email" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Gender" int4,
  "Address" jsonb
)
;

-- ----------------------------
-- Records of Customers
-- ----------------------------

-- ----------------------------
-- Table structure for DeliveryProgresses
-- ----------------------------
DROP TABLE IF EXISTS "public"."DeliveryProgresses";
CREATE TABLE "public"."DeliveryProgresses" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "CurrentLocation" jsonb,
  "PercentComplete" int2 NOT NULL,
  "EstimatedTimeRemaining" text COLLATE "pg_catalog"."default",
  "LastUpdated" timestamptz(6),
  "OrderId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of DeliveryProgresses
-- ----------------------------

-- ----------------------------
-- Table structure for Hubs
-- ----------------------------
DROP TABLE IF EXISTS "public"."Hubs";
CREATE TABLE "public"."Hubs" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "ZipCode" char(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Location" jsonb,
  "Status" int4 NOT NULL
)
;

-- ----------------------------
-- Records of Hubs
-- ----------------------------

-- ----------------------------
-- Table structure for Incidents
-- ----------------------------
DROP TABLE IF EXISTS "public"."Incidents";
CREATE TABLE "public"."Incidents" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "Description" varchar(250) COLLATE "pg_catalog"."default",
  "Status" int4 NOT NULL,
  "Time" timestamptz(6),
  "OrderHistoryId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of Incidents
-- ----------------------------

-- ----------------------------
-- Table structure for OrderHistories
-- ----------------------------
DROP TABLE IF EXISTS "public"."OrderHistories";
CREATE TABLE "public"."OrderHistories" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "Timestamp" timestamptz(6),
  "OrderId" varchar(26) COLLATE "pg_catalog"."default",
  "VehicleId" varchar(26) COLLATE "pg_catalog"."default",
  "HubId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of OrderHistories
-- ----------------------------

-- ----------------------------
-- Table structure for Orders
-- ----------------------------
DROP TABLE IF EXISTS "public"."Orders";
CREATE TABLE "public"."Orders" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "ExpectedDeliveryTime" timestamptz(6),
  "Status" int4 NOT NULL,
  "DestinationZipCode" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Distance" float8,
  "VehicleId" varchar(26) COLLATE "pg_catalog"."default",
  "CustomerId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of Orders
-- ----------------------------

-- ----------------------------
-- Table structure for Routes
-- ----------------------------
DROP TABLE IF EXISTS "public"."Routes";
CREATE TABLE "public"."Routes" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "Distance" float8,
  "StartHubId" varchar(26) COLLATE "pg_catalog"."default",
  "EndHubId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of Routes
-- ----------------------------

-- ----------------------------
-- Table structure for Staffs
-- ----------------------------
DROP TABLE IF EXISTS "public"."Staffs";
CREATE TABLE "public"."Staffs" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "Name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Phone" char(10) COLLATE "pg_catalog"."default" NOT NULL,
  "Position" int4 NOT NULL
)
;

-- ----------------------------
-- Records of Staffs
-- ----------------------------

-- ----------------------------
-- Table structure for Vehicles
-- ----------------------------
DROP TABLE IF EXISTS "public"."Vehicles";
CREATE TABLE "public"."Vehicles" (
  "Id" varchar(26) COLLATE "pg_catalog"."default" NOT NULL,
  "ZipCodeCurrent" varchar(50) COLLATE "pg_catalog"."default",
  "LicensePlate" varchar(50) COLLATE "pg_catalog"."default",
  "VehicleType" int4 NOT NULL,
  "StaffId" varchar(26) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of Vehicles
-- ----------------------------

-- ----------------------------
-- Table structure for __EFMigrationsHistory
-- ----------------------------
DROP TABLE IF EXISTS "public"."__EFMigrationsHistory";
CREATE TABLE "public"."__EFMigrationsHistory" (
  "MigrationId" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "ProductVersion" varchar(32) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of __EFMigrationsHistory
-- ----------------------------
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20230828085054_Init', '7.0.10');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20230830094309_InitBussinessEntities', '7.0.10');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."AspNetRoleClaims_Id_seq"
OWNED BY "public"."AspNetRoleClaims"."Id";
SELECT setval('"public"."AspNetRoleClaims_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."AspNetUserClaims_Id_seq"
OWNED BY "public"."AspNetUserClaims"."Id";
SELECT setval('"public"."AspNetUserClaims_Id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for AspNetRoleClaims
-- ----------------------------
SELECT setval('"public"."AspNetRoleClaims_Id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table AspNetRoleClaims
-- ----------------------------
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "public"."AspNetRoleClaims" USING btree (
  "RoleId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetRoleClaims
-- ----------------------------
ALTER TABLE "public"."AspNetRoleClaims" ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table AspNetRoles
-- ----------------------------
CREATE UNIQUE INDEX "RoleNameIndex" ON "public"."AspNetRoles" USING btree (
  "NormalizedName" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetRoles
-- ----------------------------
ALTER TABLE "public"."AspNetRoles" ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for AspNetUserClaims
-- ----------------------------
SELECT setval('"public"."AspNetUserClaims_Id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table AspNetUserClaims
-- ----------------------------
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "public"."AspNetUserClaims" USING btree (
  "UserId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetUserClaims
-- ----------------------------
ALTER TABLE "public"."AspNetUserClaims" ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table AspNetUserLogins
-- ----------------------------
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "public"."AspNetUserLogins" USING btree (
  "UserId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetUserLogins
-- ----------------------------
ALTER TABLE "public"."AspNetUserLogins" ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");

-- ----------------------------
-- Indexes structure for table AspNetUserRoles
-- ----------------------------
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "public"."AspNetUserRoles" USING btree (
  "RoleId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetUserRoles
-- ----------------------------
ALTER TABLE "public"."AspNetUserRoles" ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");

-- ----------------------------
-- Primary Key structure for table AspNetUserTokens
-- ----------------------------
ALTER TABLE "public"."AspNetUserTokens" ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");

-- ----------------------------
-- Indexes structure for table AspNetUsers
-- ----------------------------
CREATE INDEX "EmailIndex" ON "public"."AspNetUsers" USING btree (
  "NormalizedEmail" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "UserNameIndex" ON "public"."AspNetUsers" USING btree (
  "NormalizedUserName" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table AspNetUsers
-- ----------------------------
ALTER TABLE "public"."AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table Customers
-- ----------------------------
ALTER TABLE "public"."Customers" ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table DeliveryProgresses
-- ----------------------------
CREATE INDEX "IX_DeliveryProgresses_OrderId" ON "public"."DeliveryProgresses" USING btree (
  "OrderId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table DeliveryProgresses
-- ----------------------------
ALTER TABLE "public"."DeliveryProgresses" ADD CONSTRAINT "PK_DeliveryProgresses" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table Hubs
-- ----------------------------
ALTER TABLE "public"."Hubs" ADD CONSTRAINT "PK_Hubs" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table Incidents
-- ----------------------------
CREATE INDEX "IX_Incidents_OrderHistoryId" ON "public"."Incidents" USING btree (
  "OrderHistoryId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Incidents
-- ----------------------------
ALTER TABLE "public"."Incidents" ADD CONSTRAINT "PK_Incidents" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table OrderHistories
-- ----------------------------
CREATE INDEX "IX_OrderHistories_HubId" ON "public"."OrderHistories" USING btree (
  "HubId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "IX_OrderHistories_OrderId" ON "public"."OrderHistories" USING btree (
  "OrderId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "IX_OrderHistories_VehicleId" ON "public"."OrderHistories" USING btree (
  "VehicleId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table OrderHistories
-- ----------------------------
ALTER TABLE "public"."OrderHistories" ADD CONSTRAINT "PK_OrderHistories" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table Orders
-- ----------------------------
CREATE INDEX "IX_Orders_CustomerId" ON "public"."Orders" USING btree (
  "CustomerId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "IX_Orders_VehicleId" ON "public"."Orders" USING btree (
  "VehicleId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Orders
-- ----------------------------
ALTER TABLE "public"."Orders" ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table Routes
-- ----------------------------
CREATE INDEX "IX_Routes_EndHubId" ON "public"."Routes" USING btree (
  "EndHubId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "IX_Routes_StartHubId" ON "public"."Routes" USING btree (
  "StartHubId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Routes
-- ----------------------------
ALTER TABLE "public"."Routes" ADD CONSTRAINT "PK_Routes" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table Staffs
-- ----------------------------
ALTER TABLE "public"."Staffs" ADD CONSTRAINT "PK_Staffs" PRIMARY KEY ("Id");

-- ----------------------------
-- Indexes structure for table Vehicles
-- ----------------------------
CREATE INDEX "IX_Vehicles_StaffId" ON "public"."Vehicles" USING btree (
  "StaffId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Vehicles
-- ----------------------------
ALTER TABLE "public"."Vehicles" ADD CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table __EFMigrationsHistory
-- ----------------------------
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");

-- ----------------------------
-- Foreign Keys structure for table AspNetRoleClaims
-- ----------------------------
ALTER TABLE "public"."AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table AspNetUserClaims
-- ----------------------------
ALTER TABLE "public"."AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table AspNetUserLogins
-- ----------------------------
ALTER TABLE "public"."AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table AspNetUserRoles
-- ----------------------------
ALTER TABLE "public"."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table AspNetUserTokens
-- ----------------------------
ALTER TABLE "public"."AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table DeliveryProgresses
-- ----------------------------
ALTER TABLE "public"."DeliveryProgresses" ADD CONSTRAINT "FK_DeliveryProgresses_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "public"."Orders" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Incidents
-- ----------------------------
ALTER TABLE "public"."Incidents" ADD CONSTRAINT "FK_Incidents_OrderHistories_OrderHistoryId" FOREIGN KEY ("OrderHistoryId") REFERENCES "public"."OrderHistories" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table OrderHistories
-- ----------------------------
ALTER TABLE "public"."OrderHistories" ADD CONSTRAINT "FK_OrderHistories_Hubs_HubId" FOREIGN KEY ("HubId") REFERENCES "public"."Hubs" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "public"."OrderHistories" ADD CONSTRAINT "FK_OrderHistories_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "public"."Orders" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."OrderHistories" ADD CONSTRAINT "FK_OrderHistories_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "public"."Vehicles" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Orders
-- ----------------------------
ALTER TABLE "public"."Orders" ADD CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "public"."Customers" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "public"."Orders" ADD CONSTRAINT "FK_Orders_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "public"."Vehicles" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Routes
-- ----------------------------
ALTER TABLE "public"."Routes" ADD CONSTRAINT "FK_Routes_Hubs_EndHubId" FOREIGN KEY ("EndHubId") REFERENCES "public"."Hubs" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."Routes" ADD CONSTRAINT "FK_Routes_Hubs_StartHubId" FOREIGN KEY ("StartHubId") REFERENCES "public"."Hubs" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Vehicles
-- ----------------------------
ALTER TABLE "public"."Vehicles" ADD CONSTRAINT "FK_Vehicles_Staffs_StaffId" FOREIGN KEY ("StaffId") REFERENCES "public"."Staffs" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
