create table if not exists "__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table "__EFMigrationsHistory"
    owner to admin;

create table if not exists "AspNetRoles"
(
    "Id"               text not null
        constraint "PK_AspNetRoles"
            primary key,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

alter table "AspNetRoles"
    owner to admin;

create unique index if not exists "RoleNameIndex"
    on "AspNetRoles" ("NormalizedName");

create table if not exists "Customers"
(
    "Id"      varchar(26) not null
        constraint "PK_Customers"
            primary key,
    "Name"    varchar(50) not null,
    "Phone"   char(10)    not null,
    "Email"   varchar(50) not null,
    "Gender"  integer,
    "Address" jsonb
);

alter table "Customers"
    owner to admin;

create table if not exists "Hubs"
(
    "Id"       varchar(26)                               not null
        constraint "PK_Hubs"
            primary key,
    "ZipCode"  varchar(50)                               not null,
    "Location" jsonb,
    "Status"   integer                                   not null,
    "Address"  jsonb,
    "Name"     varchar(50) default ''::character varying not null
);

alter table "Hubs"
    owner to admin;

create table if not exists "Staffs"
(
    "Id"       varchar(26) not null
        constraint "PK_Staffs"
            primary key,
    "Name"     varchar(50) not null,
    "Phone"    char(10)    not null,
    "Position" integer     not null
);

alter table "Staffs"
    owner to admin;

create table if not exists "AspNetUsers"
(
    "Id"                   text    not null
        constraint "PK_AspNetUsers"
            primary key,
    "FullName"             text,
    "UserName"             varchar(256),
    "NormalizedUserName"   varchar(256),
    "Email"                varchar(256),
    "NormalizedEmail"      varchar(256),
    "EmailConfirmed"       boolean not null,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean not null,
    "TwoFactorEnabled"     boolean not null,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean not null,
    "AccessFailedCount"    integer not null,
    "ImageUrl"             text,
    "StaffId"              varchar(26)
        constraint "FK_AspNetUsers_Staffs_StaffId"
            references "Staffs"
            on delete set null
);

alter table "AspNetUsers"
    owner to admin;

create index if not exists "EmailIndex"
    on "AspNetUsers" ("NormalizedEmail");

create unique index if not exists "UserNameIndex"
    on "AspNetUsers" ("NormalizedUserName");

create index if not exists "IX_AspNetUsers_StaffId"
    on "AspNetUsers" ("StaffId");

create table if not exists "AspNetRoleClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetRoleClaims"
            primary key,
    "RoleId"     text not null
        constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            references "AspNetRoles"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table "AspNetRoleClaims"
    owner to admin;

create index if not exists "IX_AspNetRoleClaims_RoleId"
    on "AspNetRoleClaims" ("RoleId");

create table if not exists "AspNetUserClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetUserClaims"
            primary key,
    "UserId"     text not null
        constraint "FK_AspNetUserClaims_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table "AspNetUserClaims"
    owner to admin;

create index if not exists "IX_AspNetUserClaims_UserId"
    on "AspNetUserClaims" ("UserId");

create table if not exists "AspNetUserLogins"
(
    "LoginProvider"       text not null,
    "ProviderKey"         text not null,
    "ProviderDisplayName" text,
    "UserId"              text not null
        constraint "FK_AspNetUserLogins_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    constraint "PK_AspNetUserLogins"
        primary key ("LoginProvider", "ProviderKey")
);

alter table "AspNetUserLogins"
    owner to admin;

create index if not exists "IX_AspNetUserLogins_UserId"
    on "AspNetUserLogins" ("UserId");

create table if not exists "AspNetUserRoles"
(
    "UserId" text not null
        constraint "FK_AspNetUserRoles_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "RoleId" text not null
        constraint "FK_AspNetUserRoles_AspNetRoles_RoleId"
            references "AspNetRoles"
            on delete cascade,
    constraint "PK_AspNetUserRoles"
        primary key ("UserId", "RoleId")
);

alter table "AspNetUserRoles"
    owner to admin;

create index if not exists "IX_AspNetUserRoles_RoleId"
    on "AspNetUserRoles" ("RoleId");

create table if not exists "AspNetUserTokens"
(
    "UserId"        text not null
        constraint "FK_AspNetUserTokens_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "LoginProvider" text not null,
    "Name"          text not null,
    "Value"         text,
    constraint "PK_AspNetUserTokens"
        primary key ("UserId", "LoginProvider", "Name")
);

alter table "AspNetUserTokens"
    owner to admin;

create table if not exists "Routes"
(
    "Id"         varchar(26) not null
        constraint "PK_Routes"
            primary key,
    "Distance"   double precision,
    "StartHubId" varchar(26)
        constraint "FK_Routes_Hubs_StartHubId"
            references "Hubs"
            on delete cascade,
    "EndHubId"   varchar(26)
        constraint "FK_Routes_Hubs_EndHubId"
            references "Hubs"
            on delete cascade
);

alter table "Routes"
    owner to admin;

create index if not exists "IX_Routes_EndHubId"
    on "Routes" ("EndHubId");

create index if not exists "IX_Routes_StartHubId"
    on "Routes" ("StartHubId");

create table if not exists "Vehicles"
(
    "Id"             varchar(26)       not null
        constraint "PK_Vehicles"
            primary key,
    "ZipCodeCurrent" varchar(50),
    "LicensePlate"   varchar(50),
    "Type"           integer           not null,
    "StaffId"        varchar(26)
        constraint "FK_Vehicles_Staffs_StaffId"
            references "Staffs"
            on delete set null,
    "Status"         integer default 0 not null
);

alter table "Vehicles"
    owner to admin;

create index if not exists "IX_Vehicles_StaffId"
    on "Vehicles" ("StaffId");

create table if not exists "IdempotentRequests"
(
    "Id"        uuid                     not null
        constraint "PK_IdempotentRequests"
            primary key,
    "Name"      text                     not null,
    "CreatedAt" timestamp with time zone not null
);

alter table "IdempotentRequests"
    owner to admin;

create table if not exists "Phase"
(
    "Id"      varchar(26) not null
        constraint "PK_Phase"
            primary key,
    "Order"   integer     not null,
    "RouteId" varchar(26)
        constraint "FK_Phase_Routes_RouteId"
            references "Routes"
            on delete set null
);

alter table "Phase"
    owner to admin;

create table if not exists "Orders"
(
    "Id"                   varchar(26)              not null
        constraint "PK_Orders"
            primary key,
    "StartedDate"          timestamp with time zone not null,
    "ExpectedDeliveryTime" timestamp with time zone,
    "Status"               integer                  not null,
    "DestinationZipCode"   varchar(50)              not null,
    "Distance"             double precision,
    "CustomerId"           varchar(26)
        constraint "FK_Orders_Customers_CustomerId"
            references "Customers"
            on delete set null,
    "DestinationAddress"   jsonb,
    "Note"                 varchar(250),
    "PhaseId"              varchar(26)
        constraint "FK_Orders_Phase_PhaseId"
            references "Phase"
            on delete set null
);

alter table "Orders"
    owner to admin;

create index if not exists "IX_Orders_CustomerId"
    on "Orders" ("CustomerId");

create index if not exists "IX_Orders_PhaseId"
    on "Orders" ("PhaseId");

create table if not exists "DeliveryProgresses"
(
    "Id"                     varchar(26) not null
        constraint "PK_DeliveryProgresses"
            primary key,
    "CurrentLocation"        jsonb,
    "PercentComplete"        smallint    not null,
    "EstimatedTimeRemaining" text,
    "LastUpdated"            timestamp with time zone,
    "OrderId"                varchar(26)
        constraint "FK_DeliveryProgresses_Orders_OrderId"
            references "Orders"
            on delete cascade
);

alter table "DeliveryProgresses"
    owner to admin;

create index if not exists "IX_DeliveryProgresses_OrderId"
    on "DeliveryProgresses" ("OrderId");

create table if not exists "Deliveries"
(
    "Id"           varchar(26) not null
        constraint "PK_Deliveries"
            primary key,
    "DeliveryDate" timestamp with time zone,
    "OrderId"      varchar(26)
        constraint "FK_Deliveries_Orders_OrderId"
            references "Orders"
            on delete cascade,
    "VehicleId"    varchar(26)
        constraint "FK_Deliveries_Vehicles_VehicleId"
            references "Vehicles"
            on delete set null
);

alter table "Deliveries"
    owner to admin;

create table if not exists "Incidents"
(
    "Id"          varchar(26) not null
        constraint "PK_Incidents"
            primary key,
    "Description" varchar(250),
    "Status"      integer     not null,
    "Time"        timestamp with time zone,
    "DeliveryId"  varchar(26)
        constraint "FK_Incidents_Deliveries_DeliveryId"
            references "Deliveries"
            on delete set null
);

alter table "Incidents"
    owner to admin;

create index if not exists "IX_Incidents_DeliveryId"
    on "Incidents" ("DeliveryId");

create index if not exists "IX_Deliveries_OrderId"
    on "Deliveries" ("OrderId");

create index if not exists "IX_Deliveries_VehicleId"
    on "Deliveries" ("VehicleId");

create index if not exists "IX_Phase_RouteId"
    on "Phase" ("RouteId");
