{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "seq.name" . }}
    chart: {{ template "seq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "seq.fullname" . }}
{{- with .Values.rbac.rules }}
  rules:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
