environment: development

apphost: k8s

label:
  name: profio-api

container:
  name: profio-api
  pullPolicy: IfNotPresent
  image: profio-api-k8s
  tag: v1
  port: 80
replicas: 3

service:
  port: 8888
  type: ClusterIP