name: Publish Api

on:
  push:
    branches:
      - main
      - stg
    paths:
      - 'apps/Profio.Api/**'
      - 'libs/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [ stg ]

permissions: read-all

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}
    - name: Build the api image
      run: |
       echo ${{ github.repository_owner }}
       echo ${{ secrets.TOKEN }}
       docker build -f apps/Profio.Api/Dockerfile . --tag ghcr.io/hutechcj/profio-api:latest
       docker push ghcr.io/hutechcj/profio-api:latest
