name: Publish CMS

on:
  push:
    branches:
      - main
      - stg
    paths:
      - 'apps/cms/**'
      - '.github/workflows/cms.yml'
  pull_request:
    branches: [ stg ]

permissions: read-all

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}
    - name: Build the cms image
      run: |
       docker build -f apps/cms/Dockerfile . --tag ghcr.io/hutechcj/profio-cms:latest
       docker push ghcr.io/hutechcj/profio-cms:latest
